# Generated by Django 5.1.4 on 2025-03-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('motoristas', '__first__'),
        ('veiculos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Viagem', models.DateField(verbose_name='Data da Viagem')),
                ('Hora_Viagem', models.TimeField(verbose_name='Hora da Viagem')),
                ('Destino', models.CharField(max_length=500, verbose_name='Destino da Viagem')),
                ('Objetivo', models.TextField(verbose_name='Objetivo')),
                ('Passageiros', models.TextField(verbose_name='Passageiros')),
                ('Km_Inicio', models.IntegerField(blank=True, null=True, verbose_name='KM Inicio')),
                ('Km_Final', models.IntegerField(blank=True, null=True, verbose_name='KM Fim')),
                ('km_rodado', models.IntegerField(blank=True, null=True, verbose_name='KM Rodados')),
                ('Efetivada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Realizada?')),
                ('Aprovado', models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprovado')),
                ('Data_Hora_ini', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Saída')),
                ('Data_Hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Chegada')),
                ('Ocorrencias', models.TextField(blank=True, null=True, verbose_name='Ocorrencias')),
                ('DatahoraSolic', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Solicitacao')),
                ('Motorista_viag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='motoristas.motorista', verbose_name='Motorista')),
                ('Veiculo_viag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculos', verbose_name='Veiculo Utilizado')),
                ('funcionario_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_solicitante', to='funcionarios.funcionario', verbose_name='Funcionário Solicitante')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['Data_Viagem'],
            },
        ),
    ]
