# Generated by Django 5.1.4 on 2025-03-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Combustivel')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Cor Veículo')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Marca Veículo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Modelo Veículo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descricao')),
                ('chassi', models.CharField(max_length=200, verbose_name='Chassi')),
                ('anofabricacao', models.IntegerField(verbose_name='Ano Fabricação')),
                ('anomodelo', models.IntegerField(verbose_name='Ano Modelo')),
                ('datacompra', models.DateField(verbose_name='Data Aquisição')),
                ('kmManutencao', models.IntegerField(verbose_name='KM Manutenção Preventiva')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.combustivel', verbose_name='Combustível')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.cor', verbose_name='Cor do Veículo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.marca', verbose_name='Marca do Veículo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.modelo', verbose_name='Modelo do Veículo')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'ordering': ['placa'],
            },
        ),
    ]
