# Generated by Django 5.1.4 on 2025-03-12 10:45

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Motorista', models.CharField(max_length=200, verbose_name='Nome do Motorista')),
                ('CPF', cpf_field.models.CPFField(max_length=20, verbose_name='CPF do Motorista')),
                ('Data_Nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('CNH', models.CharField(verbose_name='Carteira de Habilitação')),
                ('Data_Vencimento', models.DateField(verbose_name='Data Vencimento CNH')),
                ('Categoria', models.CharField(verbose_name='Categoria da CNH')),
                ('Telefone', models.CharField(verbose_name='Telefone do Motorista')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['Nome_Motorista'],
            },
        ),
    ]
